#! /bin/zsh -i

[[ -n "${GITHUB_USER}" ]] && git config -g user.name "${GITHUB_USER}"
[[ -n "${GITHUB_EMAIL}" ]] && git config -g user.email "${GITHUB_EMAIL}"

sh -c "cd ${HOME}/mycode/dotfiles && git pull"
sh -c "cd ${HOME}/mycode/oh-my-zsh-custom && git pull"

cd ${HOME}
tmux new -s ${HOSTNAME} -n 'emacs' -d emacs
tmux new-window -d
tmux new-window -d
exec tmux attach -t ${HOSTNAME}
