#! /bin/zsh -i

[[ -n "${GITHUB_USER}" ]] && git config --global user.name "${GITHUB_USER}"
[[ -n "${GITHUB_EMAIL}" ]] && git config --global user.email "${GITHUB_EMAIL}"

[[ -z "${SKIP_PULL}" ]] && sh -c "cd ${HOME}/mycode/dotfiles && git pull"
[[ -z "${SKIP_PULL}" ]] && sh -c "cd ${HOME}/mycode/oh-my-zsh-custom && git pull"

[[ -e /var/run/docker.sock ]] && sudo chmod 777 /var/run/docker.sock

[[ -n "$1" ]] && exec $1
